### ISSUE TITLE
[1.12.2][1.4.0] Issue: Configured durability cost is incorrectly calculated

### ISSUE THREAD

**Issue by thefinaldegree** [arlyon/felling#16]
If you have a bug report, please use the template below. Otherwise just 
ignore it.

## Version Information

Substitute the [versions] for your specific details.

- Minecraft 1.12.2
- Forge: 14.23.2.2620
- Felling: 1.4.0

## Report Information

When felling a log with the following config set, the durability lost doesn't match up (examples below)

> I:"Felling Durability Cost"=1

## Steps to Reproduce

1. /give player_name minecraft:diamond_axe 1 0 {display:{Name:"Felling Testing Axe",Lore:["This is a test"]},ench:[{id:14s,lvl:3}]}
2. /give player_name minecraft:diamond_axe 1 0 {display:{Name:"Regular Testing Axe",Lore:["This is a test"]}}
3. Place two oak(or any) log pillars down (2 blocks tall), making sure to put more space between them than the configured gap (I:"Maximum Blocks Between Trees")
4. Break one pillar with the Felling Axe, another with the Regular Axe

## Forge Log

Nothing present in Forge Log

## Extra Data Collected
Here are my results from testing the different enchantment levels (these are all from a Diamond Axe):

### Felling 3:
Blocks felled: 11
Durability Before: 1561 / 1561
Durability After: 1196 / 1561
Durability Lost: 365

Blocks felled: 2
Durability Before: 1561 / 1561
Durability After: 1435 / 1561
Durability Lost: 126

### Felling 2: 
Blocks felled: 2
Durability Before: 1561 / 1561
Durability After: 1523 / 1561
Durability Lost: 38

### Felling 1: 
Blocks felled: 2
Durability Before: 1561 / 1561
Durability After: 1555 / 1561
Durability Lost: 6

**Comment by arlyon** [comment]
You are absolutely correct looks like in the refactor a block of code ended up outside an if statement which meant it was charging durability for each visited block, instead of each broken block. Thanks for taking the time to collect the data.

Fix inc.

**Comment by mrgrim** [comment]
Sorry to necro, but this seems like a good reason for a 1.4.1 release. I didn't see this issue and spent quite some down tracking down the cause until I finally built the current git version myself and failed to reproduce it.

**Comment by arlyon** [comment]
Sorry to hear you've been having issues. Dont worry about necro; I had some additional features going but I got overrun with work and never found time to get back to it. New version published :)
