### ISSUE TITLE
[Compat] Enchantment Descriptions

### ISSUE THREAD

**Issue by CREEATION** [arlyon/felling#21]
![2019-03-25_09 58 27](https://user-images.githubusercontent.com/3277769/54906900-9886ec80-4ee4-11e9-8add-40d4304715dc.png)

Mod: [Enchantment Descriptions](https://minecraft.curseforge.com/projects/enchantment-descriptions/)

This is also the case for Veining.

**Comment by arlyon** [comment]
If you'd like to add them, you may do so here and I'll merge your PR
https://github.com/arlyon/felling/blob/1.12.x/src/main/resources/assets/felling/lang/en_US.lang
