### ISSUE TITLE
config spam

### ISSUE THREAD

**Issue by jjc54** [arlyon/felling#4]
MC: 1.12
Forge: forge-14.21.1.2420
Felling: felling-1.3.0-1.12
Issue: I keep getting spammed with this config message every time I break a block. Happens on my old world and on a freshly generated one.
Imgur: http://imgur.com/a/6HOja

**Comment by arlyon** [comment]
Did you update the mod, or download it fresh? My initial thoughts are that the config files aren't correct.

**Comment by arlyon** [comment]
For now just do what it says and change the settings in the config to resend the config to the server and I'll try and find a fix.

**Comment by jjc54** [comment]
I updated the mod from the immediately previous version. My problem is that these are single player worlds and I already tried deleting my config/letting it regenerate and then trying out both my world and a fresh one.

**Comment by arlyon** [comment]
Yeah just go into the mod settings and change the clientside config which will trigger the game to resend it and get rid of the message. Basically there's a setting that the server needs that isn't being sent properly on world start. I'll get a fix out tomorrow but it's late here.

**Comment by jjc54** [comment]
Mmk I'll try your fix!

**Comment by rckymtnrfc** [comment]
I tried changing settings in the config (in both the client side and server side section) but I'm still seeing the chat spam when breaking blocks.

**Comment by ghost** [comment]
Having this problem as well on a brand new instance and world. Mc 1.12.2

**Comment by arlyon** [comment]
Yeah it's just a problem with the build. I knew it before I built it which is why its alpha. Its on the todo list but I am swamped with work at the moment.

**Comment by ghost** [comment]
np.  I'll go back to a previous version until then :-)

**Comment by arlyon** [comment]
Problem identified and closed. Took a while! But I finally found some time for a fix.
