### ISSUE TITLE
[1.12] Paxel Problems

### ISSUE THREAD

**Issue by KajesLorian** [arlyon/felling#5]
When placing Felling on a Mekanism Paxel redstone is not mined, but rather "disappears" until right-clicked. The Felling enchant (and the veining enchant) both work on the same paxel simultaneously for trees and ores otherwise; attempted to recreate error on other ores and they all worked fine, including ores like coal and lapis. Veining by itself also works fine.

Felling-1.2.3
Mekanism-1.12.1-9.4.1.326

**Comment by arlyon** [comment]
I'll have a look soon.

**Comment by arlyon** [comment]
Just an update on this. Made a few sweeping changes to the code that should improve compatibility. Going to clean up veining next and come back to this.

**Comment by arlyon** [comment]
Confirmed fixed in previous release
